from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

import spotipy
from spotipy.oauth2 import SpotifyOAuth

# Authenticate with YouTube
flow = InstalledAppFlow.from_client_secrets_file(
    "client_secret.json",
    scopes=["https://www.googleapis.com/auth/youtube.readonly"]
)
creds = flow.run_local_server(port=0)
youtube = build("youtube", "v3", credentials=creds)

# Authenticate with Spotify
sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
    client_id="xxx",
    client_secret="xxx",
    redirect_uri="http://127.0.0.1:8888/callback",
    scope="playlist-modify-public playlist-modify-private"
))
user_id = sp.current_user()["id"]

# Get all my playlists from YouTube
playlists = []
next_page_token = None

while True:
    request = youtube.playlists().list(
        part="snippet,contentDetails",
        mine=True,
        maxResults=50,
        pageToken=next_page_token
    )
    response = request.execute()
    playlists.extend(response["items"])
    next_page_token = response.get("nextPageToken")
    if not next_page_token:
        break

# Get all song titles + artists from each item in the playlists
def get_playlist_songs(playlist_id):
    songs = []
    next_page_token = None
    while True:
        pl_request = youtube.playlistItems().list(
            part="snippet",
            playlistId=playlist_id,
            maxResults=50,
            pageToken=next_page_token
        )
        pl_response = pl_request.execute()
        for item in pl_response['items']:
            video_title = item['snippet']['title']
            video_id = item['snippet']['resourceId']['videoId']

            # Get video details
            vid_request = youtube.videos().list(
                part="snippet",
                id=video_id
            )
            vid_response = vid_request.execute()

            # If videos are privated / deleted this field won't get filled in
            if vid_response['items']:
                channel_title = vid_response['items'][0]['snippet']['channelTitle']
            else:
                channel_title = ""

            songs.append({"title": video_title, "channel": channel_title})
        next_page_token = pl_response.get("nextPageToken")
        if not next_page_token:
            break
    return songs

playlist_2 = [pl for pl in playlists if "prius" in pl["snippet"]["title"].lower()]

# Spotify search is weird with special characters and some
def sanitize_song(song):
    # Remove " - Topic", parentheses content, etc.
    song = song.replace(" - Topic", "")
    import re
    song = re.sub(r"\(.*?\)", "", song)  # remove everything in parentheses
    return song.strip()

def find_song_on_spotify(uri_list, song_clean):
    if " - " in song_clean:
        artist, title = song_clean.split(" - ", 1)
    else:
        artist, title = "", song_clean
    
    query = f"track:{title} artist:{artist}"
    results = sp.search(q=query, type="track", limit=5) # try more than 1
    if results['tracks']['items']:
        uri_list.append(results['tracks']['items'][0]['uri'])
    else:
        print(f"Not found: {song}")

# Spotify will only add 100 songs to a playlist at a time
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

# Move each playlist to Spotify
for pl in playlist_2:
    playlist_title = pl["snippet"]["title"]
    playlist_id = pl["id"]
    print(f"\nPlaylist: {playlist_title}")

    # Create matching playlist on Spotify
    playlist = sp.user_playlist_create(
        user=user_id,
        name=playlist_title,
        public=True,
        description="Generated by https://github.com/nickbakeruvic/music-transfer"
    )

    spotify_uris = []
    songs = get_playlist_songs(playlist_id)
    for song in songs:
        song_str = f"{song['channel']} - {song['title']}"
        song_clean = sanitize_song(song_str)
        find_song_on_spotify(spotify_uris, song_clean)

    if len(spotify_uris) > 0:
        for batch in chunks(spotify_uris, 100):
            sp.playlist_add_items(playlist_id=playlist['id'], items=batch)